### ISSUE TITLE
Class class com.google.common.hash.BloomFilter is not a valid POJO type

### ISSUE THREAD

**Issue by PerSun-Mei** [stratosphere/rdfind#1]
Hello,I have a question,why do the compiler appear this error "Class class com.google.common.hash.BloomFilter is not a valid POJO type" when running the rdfind project?

**Comment by sekruse** [comment]
Hi, I haven't looked at the code in years, but if I remember correctly, RDFind is passing sending Bloom filters via Apache Flink.

This [Stackoverflow question](https://stackoverflow.com/questions/53615246/apache-flink-what-does-class-x-does-not-contain-a-setter-for-field-y-mean) indicates that this is not an error. It's only a warning that Flink can't do certain optimizations with the `BloomFilter` class.

**Comment by PerSun-Mei** [comment]
OK,OK,Thanks! I have known how to deal  with it.
