### ISSUE TITLE
The output ARs and CINDs is null.

### ISSUE THREAD

**Issue by PerSun-Mei** [stratosphere/rdfind#2]
Hi, I have another question. When I ran this code, I tried to  get the CINDs in files by appending the parameter  ’--output [output file path]‘ , but it didn't work, the output file is empty. So I want to ask you how can I get the CINDs.

**Comment by sekruse** [comment]
I don't really remember what to do here, but that sounds about right what you're doing. Is it possible that there are simply no CINDs in your input file?

**Comment by PerSun-Mei** [comment]
> I don't really remember what to do here, but that sounds about right what you're doing. Is it possible that there are simply no CINDs in your input file?

I think it is impossible，because the dataset is from the link in your papers，so is it possible there exsits other reasons?

**Comment by PerSun-Mei** [comment]
[runlogs.log](https://github.com/stratosphere/rdfind/files/6268188/runlogs.log)
This is  running logs.Or can you spare some time to look at it for finding what problem it is?

**Comment by sekruse** [comment]
Here are some parameters that might be worth double-checking:

* `--support`: The min support is set to 10. Might be worth trying with a lower value, e.g., `1`, for testing purposes.
* `--tabs`: if your input file uses tabs
* `--debug-level`: set to `1` to get additional debug logs

**Comment by PerSun-Mei** [comment]
I have tried these parameters but it didn't work, but I found there is a parameter related with prefixFile, is it possible because of the parameter 'prefixFilePaths'? I didn't assign values to it.

**Comment by sekruse** [comment]
Find the parameter explanations [here](https://github.com/stratosphere/rdfind/blob/67b691a834f72a76d4bcbef774e67e507f2d79d8/rdfind-algorithm/src/main/scala/de/hpi/isg/sodap/rdfind/programs/RDFind.scala#L639). `prefixFilePaths` only replaces URLs with short-hand forms and shouldn't affect the result.

I'm afraid I need more context, e.g., the file that you're running on, the exact command that you're using, and the output that you're seeing. Also, please understand that I have only little time to look into this.

**Comment by PerSun-Mei** [comment]
Thank you very much for your time!

The input dataset is DB14-MPCE from the link [https://hpi.de//naumann/projects/repeatability/
data-profiling/cind-discovery-on-rdf-data.html](url) which is given in your paper.

The execution command like this:

> java -Djava.rmi.server.hostname=ubuntu16.05xujb \
        -Dlog4j.configuration="file:/home/ubuntu/sunlimei/logs/log4j.properties" \
        -cp "lib/*" \
        de.hpi.isg.sodap.rdfind.programs.RDFind \
        /home/ubuntu/sunlimei/datas/mappingbased_properties_cleaned_en.nt \
        -rex 127.0.0.1:6123 \
		-dop 1 \
		--use-fis \
		--collect-result \
		--output /home/ubuntu/sunlimei/outputs/cinds \
		--support 2 \
		--traversal-strategy 2 \
		--find-frequent-captures \
        -jar lib/rdfind-algorithm-0.0.2-SNAPSHOT.jar lib/rdfind-flink-0.0.2-SNAPSHOT.jar lib/rdfind-util-0.0.2-SNAPSHOT.jar  lib/fastutil-6.5.15.jar lib/rdf-converter-0.0.2-SNAPSHOT.jar lib/guava-19.0-sekruse-SNAPSHOT.jar

The output is an empty file.

**Comment by sekruse** [comment]
I took another look at your log file from comment #

> [runlogs.log](https://github.com/stratosphere/rdfind/files/6268188/runlogs.log)
> This is running logs.Or can you spare some time to look at it for finding what problem it is?

I took another look at this log file and noticed that it finished suspiciously fast. In fact, even the reading part finished in less than a second:

```
grep -E '\d\d/.*DataSource.*switched to' runlogs.log 
04/07/2021 08:40:22	CHAIN DataSource (Read input files) -> Filter (Filter comments)(1/8) switched to SCHEDULED 
04/07/2021 08:40:22	CHAIN DataSource (Read input files) -> Filter (Filter comments)(1/8) switched to DEPLOYING 
04/07/2021 08:40:22	CHAIN DataSource (Read input files) -> Filter (Filter comments)(2/8) switched to SCHEDULED 
04/07/2021 08:40:22	CHAIN DataSource (Read input files) -> Filter (Filter comments)(2/8) switched to DEPLOYING 
04/07/2021 08:40:22	CHAIN DataSource (Read input files) -> Filter (Filter comments)(3/8) switched to SCHEDULED 
04/07/2021 08:40:22	CHAIN DataSource (Read input files) -> Filter (Filter comments)(3/8) switched to DEPLOYING 
04/07/2021 08:40:22	CHAIN DataSource (Read input files) -> Filter (Filter comments)(4/8) switched to SCHEDULED 
04/07/2021 08:40:22	CHAIN DataSource (Read input files) -> Filter (Filter comments)(4/8) switched to DEPLOYING 
04/07/2021 08:40:22	CHAIN DataSource (Read input files) -> Filter (Filter comments)(5/8) switched to SCHEDULED 
04/07/2021 08:40:22	CHAIN DataSource (Read input files) -> Filter (Filter comments)(5/8) switched to DEPLOYING 
04/07/2021 08:40:22	CHAIN DataSource (Read input files) -> Filter (Filter comments)(6/8) switched to SCHEDULED 
04/07/2021 08:40:22	CHAIN DataSource (Read input files) -> Filter (Filter comments)(6/8) switched to DEPLOYING 
04/07/2021 08:40:22	CHAIN DataSource (Read input files) -> Filter (Filter comments)(7/8) switched to SCHEDULED 
04/07/2021 08:40:22	CHAIN DataSource (Read input files) -> Filter (Filter comments)(7/8) switched to DEPLOYING 
04/07/2021 08:40:22	CHAIN DataSource (Read input files) -> Filter (Filter comments)(8/8) switched to SCHEDULED 
04/07/2021 08:40:22	CHAIN DataSource (Read input files) -> Filter (Filter comments)(8/8) switched to DEPLOYING 
04/07/2021 08:40:22	CHAIN DataSource (Read input files) -> Filter (Filter comments)(4/8) switched to RUNNING 
04/07/2021 08:40:22	CHAIN DataSource (Read input files) -> Filter (Filter comments)(5/8) switched to RUNNING 
04/07/2021 08:40:22	CHAIN DataSource (Read input files) -> Filter (Filter comments)(8/8) switched to RUNNING 
04/07/2021 08:40:22	CHAIN DataSource (Read input files) -> Filter (Filter comments)(2/8) switched to RUNNING 
04/07/2021 08:40:22	CHAIN DataSource (Read input files) -> Filter (Filter comments)(6/8) switched to RUNNING 
04/07/2021 08:40:22	CHAIN DataSource (Read input files) -> Filter (Filter comments)(7/8) switched to RUNNING 
04/07/2021 08:40:22	CHAIN DataSource (Read input files) -> Filter (Filter comments)(3/8) switched to RUNNING 
04/07/2021 08:40:22	CHAIN DataSource (Read input files) -> Filter (Filter comments)(1/8) switched to RUNNING 
04/07/2021 08:40:22	CHAIN DataSource (Read input files) -> Filter (Filter comments)(1/8) switched to FINISHED 
04/07/2021 08:40:22	CHAIN DataSource (Read input files) -> Filter (Filter comments)(5/8) switched to FINISHED 
04/07/2021 08:40:22	CHAIN DataSource (Read input files) -> Filter (Filter comments)(8/8) switched to FINISHED 
04/07/2021 08:40:22	CHAIN DataSource (Read input files) -> Filter (Filter comments)(2/8) switched to FINISHED 
04/07/2021 08:40:22	CHAIN DataSource (Read input files) -> Filter (Filter comments)(3/8) switched to FINISHED 
04/07/2021 08:40:22	CHAIN DataSource (Read input files) -> Filter (Filter comments)(4/8) switched to FINISHED 
04/07/2021 08:40:22	CHAIN DataSource (Read input files) -> Filter (Filter comments)(6/8) switched to FINISHED 
04/07/2021 08:40:22	CHAIN DataSource (Read input files) -> Filter (Filter comments)(7/8) switched to FINISHED 
```

[The file is 4.33 GiB in size](https://hpi.de//naumann/projects/repeatability/data-profiling/cind-discovery-on-rdf-data.html), so that seems rather fast. My guess is that Flink doesn't even read the (right) file and subsequently operates with no data at all. That would explain why there are no CINDs in the end. Perhaps try adding a `file:` in front of you input and output paths on the command line.

**Comment by PerSun-Mei** [comment]
Thank you very much! I have solved my problem under your guidance.

**Comment by sekruse** [comment]
Glad to hear it works now!
